apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev # Ensure this matches your deployment namespace
type: Opaque
data:
  username: YWRtaW4=
  password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=