apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev # Ensure this matches your deployment namespace
type: Opaque
data:

  # Database Secrets
  username: YWRtaW4=
  password: eW91cl9zZWN1cmVfcGFzc3dvcmQ=

  # MinIO Secrets
  minio-access-key: YWRtaW4=
  minio-secret-key: cGFzc3dvcmQxMjM=